### PR TITLE
Custom file comparison

### PR DESCRIPTION
**Pull request by BenjaminHabert**
Allow user to provide a custom comparison function to `FileSnapshot`.

This can be usefull if the file being snapshot-tested contains meta-data that is irrelevent to the user. An example of usage was added to `exemples/pytest/test_demo.py`.

Closes: #96

### CODE REVIEW

**Comment by gurunars** [comment]
As arrogant as it may sound but you are applying a fix to a wrong place.

You need to fix the approach you use to generate and store the screenshots and audio-files so that they store only the data that is relevant for your tests.

By definition, if during verification you are able to say which parts of the payload are important, you also are able to say it during a serialization phase. 

I.e. you need to extract the entity that you would otherwise compare using a custom comparison routine and serialize that entity instead of the whole thing.

I wouldn't introduce this feature.

**Comment by paulmelnikow** [comment]
Hi! Thanks for the contribution. Like @gurunars I'm not thrilled about adding this feature. Although, I can see some justification for it, for example normalizing newlines, or stripping/normalizing metadata.

Would it be possible to implement this as a transform function that is run on the file?

If for your use case it really needs to be a custom comparator, I wonder if that kind of functionality absolutely needs to be in this library.

Or alternatively, is there something snapshottest could expose to help you load the data from the snapshot, with which you could then write your own assertions?

**Comment by BenjaminHabert** [comment]
Hello. I  understand if you prefer  not to include this feature and close the pull request, no problem.

Your suggestion of an easy way to load data from the snapshot would also solve my problem.

To give you a better understanding of why I added the feater, here is the use case I was working with:
- my python application code generates an html file containing images and graphs
- I want to test that the webpage generated stays **visually** the same; if it changes I want to see the diff in the pull request
  - this makes it easy to accept / reject the change when discussing with the team or client
- I use a third-party tool to create an image (screenshot) of the webpage : this is want is compared by `snapshottest`
- because I do not have full controle on this third-party tool, the image is allways slightly different:
  - metadata changes
  - slight pixel variations of the image; for instance everything is shifted by 1 pixel
- consequently, I needed a custom comparison function that can compare two images and decide if they are at leat 99% similar

**Comment by paulmelnikow** [comment]
It makes sense that a transform will not work and that you need to write your own comparator function

It's not quite clear from the diff how this would make writing that type of test more convenient. How would you invoke this functionality from your tests?

**Comment by paulmelnikow** [comment]
See a similar request in #38.

**Comment by paulmelnikow** [comment]
Let's discuss in #38 and circle back.

**Pull request closed without merging**
