### PR TITLE
Allow snapshot to be modified before write

### LINKED ISSUE #89: Conflicts with black
Hi! Thanks for this useful tool!

When I save out new snapshots, they aren't in the format recognized by Black, which involves running the formatter a second time. This is a little fiddly, and I don't really care about having the format just so, so I would prefer to automatically ignore these files.

Some possible solutions:

1. Add
    ```py
    # fmt: off
    ```
    to the block at the top of the snapshot file. I've tested this, it works, and it's easy.
2. Let people decide whether they want this header. I'd turn it on by default – since it's a good default – and let people turn it off if they _really_ want their files formatted by Black.
3. If Black is available, before writing the file, attempt to run the output through Black. Let users disable this behavior in config. I like this option best because it's a very nice developer experience (even though it would be a little inconvenient for my use case, which sadly is a lib that has Python 2 deps, so I can't run tests and Black in the same env).
4. Try to modify the output to cohere to Black's demands. I expect this is impractical.

With some guidance about which way to go, I'd be happy to contribute this.

### PR DESCRIPTION
**Pull request by kam193**
This PR introduced simple callbacks which can be used to modify content of the snapshot file before write it.

The main purpose is to allow formatting files (see example with black usage), so it probably can close #89

### CODE REVIEW

**Comment by kam193** [comment]
Hi, @paulmelnikow I want you to ask what do you think about change like this :)

**Comment by wowkin2** [comment]
Any progress on this PR? @paulmelnikow @syrusakbary

**Comment by wowkin2** [comment]
@kam193 can you update this PR, so it can be merged later?

**Review by ayys — APPROVED** [review]
This is pretty cool. The code looks generally good to me. Approved!~

**Pull request merged**
