### PR TITLE
Features/django testcase integration [W.I.P]

### LINKED ISSUE #1: django.test.TestCase support
First off great library can't wait to integrate it into my project!

I think theres a bug where testcase doesn't reset after each test.

The following code will print out 0, 1, 2 
showing that the market models are not being deleted after each test

```python
class MasterDatabaseNodeTestCase(TestCase):
    def setUp(self):
        print(Markets.objects.count()

        market = Markets(name='SF')
        market.save()
        self.market = market
   
    def test_1(self):
         self.assertTrue(True)

    def test_2(self):
         self.assertTrue(True)

    def test_3(self):
         self.assertTrue(True)
```

I looked a little in to the source code for the testCase implementation

should
https://github.com/syrusakbary/snapshottest/blob/master/snapshottest/unittest.py#L83
be calling super().setUp()

and

https://github.com/syrusakbary/snapshottest/blob/master/snapshottest/unittest.py#L97
be calling super().tearDown()?

### PR DESCRIPTION
**Pull request by BossGrand**
This is my proposal for django testcase integration, resolves #1

wanted to post this to get feedback

current there is no way to update the snapshots. I'm going to add a management.py command that will do this

### CODE REVIEW

**Comment by BossGrand** [comment]
Theres not a very good way to add arguments to the python manage.py test

Personally I've decided to switch my project to use py.test

This solution is close, but I'm not going to devote more time to it atm. Feel free to close this.

**Comment by jsep** [comment]
@BossGrand please test my PR (#4) to see if that fits your needs.
Thanks

**Comment by audiolion** [comment]
#4 is the same as this PR and is merged so this can probably be closed now

**Comment by syrusakbary** [comment]
@audiolion you're right.
Closing this PR :)

**Pull request closed without merging**
